

export const ADD_TO_BE_APPROVED = "ADD_TO_BE_APPROVED";

export const REMOVE_TO_BE_APPROVED= "REMOVE_TO_BE_APPROVED";

export const SAVE_APPROVED = "SAVE_APPROVED";

export const CREATE_APPROVAL_REQUEST = "CREATE_APPROVAL_REQUEST";

export const CREATE_APPROVAL_SUCCESS= "CREATE_APPROVAL_SUCCESS";

export const CREATE_APPROVAL_FAIL= "CREATE_APPROVAL_FAIL";

export const CLEAR_ERRORS= "CLEAR_ERRORS";

export const MY_APPROVALS_REQUEST = "MY_APPROVALS_REQUEST";

export const MY_APPROVALS_SUCCESS = "MY_APPROVALS_SUCCESS";

export const MY_APPROVALS_FAIL = "MY_APPROVALS_FAIL";

export const ALL_APPROVALS_REQUEST = "ALL_APPROVALS_REQUEST";

export const ALL_APPROVALS_SUCCESS = "ALL_APPROVALS_SUCCESS";

export const ALL_APPROVALS_FAIL = "ALL_APPROVALS_FAIL";

export const UPDATE_APPROVAL_REQUEST = "UPDATE_APPROVAL_REQUEST";

export const UPDATE_APPROVAL_SUCCESS = "UPDATE_APPROVAL_SUCCESS";

export const UPDATE_APPROVAL_RESET = "UPDATE_APPROVAL_RESET";

export const UPDATE_APPROVAL_FAIL = "UPDATE_APPROVAL_FAIL";

export const DELETE_APPROVAL_REQUEST = "DELETE_APPROVAL_REQUEST";

export const DELETE_APPROVAL_SUCCESS = "DELETE_APPROVAL_SUCCESS";

export const DELETE_APPROVAL_RESET = "DELETE_APPROVAL_RESET";

export const DELETE_APPROVAL_FAIL = "DELETE_APPROVAL_FAIL";

export const APPROVAL_DETAILS_REQUEST = "APPROVAL_DETAILS_REQUEST";

export const APPROVAL_DETAILS_SUCCESS = "APPROVAL_DETAILS_SUCCESS";

export const APPROVAL_DETAILS_FAIL = "APPROVAL_DETAILS_FAIL";

export const HANDLE_SUBMIT_APPROVAL = "HANDLE_SUBMIT_APPROVAL";

